import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

export const supportedExtensionLanguages = ['node', 'python', 'ruby', 'java', 'dotnet', 'go'] as const;
export type SupportedExtensionLanguage = (typeof supportedExtensionLanguages)[number];

export interface ExtensionScaffoldOptions {
  name: string;
  language: SupportedExtensionLanguage;
  directory: string;
}

const commonFiles = {
  '.gitignore': `node_modules\ncoverage\ndist\n.env\n__pycache__/\n*.pyc\nbin/\nobj/\n`,
  '.env.example': `KIKET_EXTENSION_SECRET=\n`,
  'README.md': (name: string, language: string) => `# ${name}

Extension scaffold generated by the TypeScript Kiket CLI.

## Strategy

This scaffold is intentionally minimal, testable, and production-friendly:

- one entrypoint
- one example test
- one CI workflow stub
- one place to document configuration

## Language

${language}

## Future Vision

- keep handler logic pure where possible
- isolate transport concerns from business logic
- prefer contract tests against Kiket webhook payloads
`,
};

const languageFiles: Record<SupportedExtensionLanguage, Record<string, string>> = {
  node: {
    'package.json': JSON.stringify(
      {
        name: 'kiket-extension',
        private: true,
        type: 'module',
        scripts: {
          build: 'tsc',
          test: 'vitest run',
          dev: 'tsx watch src/handler.ts',
        },
        devDependencies: {
          typescript: '^5.9.3',
          vitest: '^3.2.0',
          tsx: '^4.20.6',
        },
      },
      null,
      2,
    ),
    'tsconfig.json': JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2023',
          module: 'ESNext',
          moduleResolution: 'Bundler',
          strict: true,
          outDir: 'dist',
        },
        include: ['src/**/*.ts', 'tests/**/*.ts'],
      },
      null,
      2,
    ),
    'src/handler.ts': `export interface KiketExtensionEvent {
  eventType: string;
  payload: Record<string, unknown>;
}

export async function handleEvent(event: KiketExtensionEvent) {
  return {
    status: 'ok',
    message: \`Handled \${event.eventType}\`,
  };
}
`,
    'tests/handler.test.ts': `import { describe, expect, it } from 'vitest';
import { handleEvent } from '../src/handler.js';

describe('handleEvent', () => {
  it('returns a successful response', async () => {
    await expect(handleEvent({ eventType: 'issue.created', payload: {} })).resolves.toMatchObject({
      status: 'ok',
    });
  });
});
`,
    '.github/workflows/test.yml': `name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: pnpm install
      - run: pnpm test
`,
  },
  python: {
    'requirements.txt': `pytest>=8.0.0\n`,
    'src/handler.py': `def handle_event(event: dict) -> dict:
    return {"status": "ok", "message": f"Handled {event.get('eventType', 'unknown')}"}
`,
    'tests/test_handler.py': `from src.handler import handle_event

def test_handle_event():
    result = handle_event({"eventType": "issue.created"})
    assert result["status"] == "ok"
`,
    '.github/workflows/test.yml': `name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: pytest
`,
  },
  ruby: {
    'Gemfile': `source 'https://rubygems.org'\ngem 'rspec'\n`,
    'lib/handler.rb': `module KiketExtension
  def self.handle_event(event)
    { status: 'ok', message: "Handled #{event['eventType']}" }
  end
end
`,
    'spec/handler_spec.rb': `require_relative '../lib/handler'

RSpec.describe KiketExtension do
  it 'handles an event' do
    expect(described_class.handle_event({ 'eventType' => 'issue.created' })[:status]).to eq('ok')
  end
end
`,
    '.github/workflows/test.yml': `name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - run: bundle install
      - run: bundle exec rspec
`,
  },
  java: {
    'pom.xml': `<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>dev.kiket</groupId>
  <artifactId>kiket-extension</artifactId>
  <version>1.0.0</version>
</project>
`,
    'src/main/java/dev/kiket/Handler.java': `package dev.kiket;

public class Handler {
  public static String handleEvent(String eventType) {
    return "Handled " + eventType;
  }
}
`,
    'src/test/java/dev/kiket/HandlerTest.java': `package dev.kiket;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

class HandlerTest {
  @Test
  void handlesEvent() {
    assertEquals("Handled issue.created", Handler.handleEvent("issue.created"));
  }
}
`,
    '.github/workflows/test.yml': `name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - run: mvn test
`,
  },
  dotnet: {
    'Extension.csproj': `<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
</Project>
`,
    'Handler.cs': `public static class Handler {
  public static string HandleEvent(string eventType) => $"Handled {eventType}";
}
`,
    'Tests/HandlerTests.cs': `using Xunit;

public class HandlerTests {
  [Fact]
  public void HandlesEvent() {
    Assert.Equal("Handled issue.created", Handler.HandleEvent("issue.created"));
  }
}
`,
    '.github/workflows/test.yml': `name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - run: dotnet test
`,
  },
  go: {
    'go.mod': `module kiket-extension

go 1.24
`,
    'main.go': `package main

func HandleEvent(eventType string) string {
	return "Handled " + eventType
}
`,
    'main_test.go': `package main

import "testing"

func TestHandleEvent(t *testing.T) {
	if HandleEvent("issue.created") != "Handled issue.created" {
		t.Fatal("unexpected response")
	}
}
`,
    '.github/workflows/test.yml': `name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - run: go test ./...
`,
  },
};

export async function scaffoldExtension(options: ExtensionScaffoldOptions): Promise<void> {
  await mkdir(options.directory, { recursive: true });

  for (const [relativePath, value] of Object.entries(commonFiles)) {
    const content = typeof value === 'function' ? value(options.name, options.language) : value;
    await writeScaffoldFile(options.directory, relativePath, content);
  }

  for (const [relativePath, content] of Object.entries(languageFiles[options.language])) {
    await writeScaffoldFile(options.directory, relativePath, content);
  }
}

async function writeScaffoldFile(root: string, relativePath: string, content: string) {
  const fullPath = join(root, relativePath);
  await mkdir(dirname(fullPath), { recursive: true });
  await writeFile(fullPath, content);
}
