# Prevent inheritance from parent directory configs
inherit_from: ~

require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/kiket/commands/**/*'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'lib/kiket/commands/**/*'

Metrics/ClassLength:
  Max: 300
  Exclude:
    - 'lib/kiket/commands/**/*'

Metrics/ModuleLength:
  Max: 300

Metrics/AbcSize:
  Max: 50
  Exclude:
    - 'lib/kiket/commands/**/*'

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'lib/kiket/commands/**/*'

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - 'lib/kiket/commands/**/*'

Gemspec/DevelopmentDependencies:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

RSpec/ExampleLength:
  Max: 60

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 5

RSpec/AnyInstance:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Capybara/RSpec/PredicateMatcher:
  Enabled: false
