# Prevent inheritance from parent directory configs
inherit_from: []

plugins:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Include:
    - '**/*.rb'
    - '*.gemspec'
    - 'Gemfile'
    - 'Rakefile'
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/*'

# Disable Rails cops - this is a CLI, not a Rails app
Rails/Exit:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/Present:
  Enabled: false

Rails/Blank:
  Enabled: false

# Allow naming patterns specific to CLI tools
Naming/PredicateMethod:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/FileName:
  Exclude:
    - '**/Gemfile'
    - '**/Rakefile'

# CLI uses safe navigation chains in output handling
Style/SafeNavigationChainLength:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 210

# Allow short parameter names in specific contexts
Naming/MethodParameterName:
  AllowedNames:
    - ms
    - id
    - io
    - db

# CLI has complex APIs with many options
Metrics/ParameterLists:
  Max: 8
  Exclude:
    - 'lib/kiket/commands/**/*'
    - 'lib/kiket/definition_testing.rb'

# Performance cop - disable for simple array literals
Performance/CollectionLiteralInLoop:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/kiket/commands/**/*'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 80
  Exclude:
    - 'lib/kiket/commands/**/*'
    - 'lib/kiket/definition_testing.rb'

Metrics/ClassLength:
  Max: 300
  Exclude:
    - 'lib/kiket/commands/**/*'

Metrics/ModuleLength:
  Max: 300

Metrics/AbcSize:
  Max: 100
  Exclude:
    - 'lib/kiket/commands/**/*'
    - 'lib/kiket/definition_testing.rb'

Metrics/CyclomaticComplexity:
  Max: 35
  Exclude:
    - 'lib/kiket/commands/**/*'
    - 'lib/kiket/definition_testing.rb'

Metrics/PerceivedComplexity:
  Max: 35
  Exclude:
    - 'lib/kiket/commands/**/*'
    - 'lib/kiket/definition_testing.rb'

Gemspec/DevelopmentDependencies:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

RSpec/ExampleLength:
  Max: 60

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 5

RSpec/AnyInstance:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/SpecFilePathSuffix:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false
